### PR TITLE
check_apt_security_updates script handles broken

### PR DESCRIPTION
**Pull request by jcbashdown**
When there are broken packages apt-check returns a string, not an int.
This causes a exit code of 3 and an unknown alert due to an exception on
string parsing. This should be a
critical.

### CODE REVIEW

**Comment by jcbashdown** [comment]
Closing until I sort out a test

**Comment by tombooth** [comment]
Looks reasonable to me, have a run it past @alphagov/team-infrastructure-admins ?

**Comment by samjsharpe** [comment]
It looked very reasonable to me, so [I released it](https://pypi.python.org/pypi/gds-nagios-plugins/1.3.1)

**Comment by jcbashdown** [comment]
@samjsharpe Awesome, cheers! :eggplant:

**Pull request merged**
